language: clojure
lein: 2.8.3
dist: xenial
services:
  - postgresql
before_script:
  - psql -c 'create database ${POSTGRES_DB};' -U postgres
jdk:
  -openjdk8
script: lein do cljfmt check, eastwood, test
deploy:
  provider: script
  skip_cleanup: true
  script: lein deploy
  on:
    tags: true
cache:
  directories:
    - $HOME/.m2
